# Summarize the results from the run_exp1d.sh script by parsing the 
# analysis.txt files and plotting CNC and Win correct vs. OOV penalty.
# Generated by Gemini: https://gemini.google.com/share/354108138ea4

import os
import glob
import re
import matplotlib.pyplot as plt
from absl import app
from absl import flags
from absl import logging

# Define command line flags
FLAGS = flags.FLAGS
flags.DEFINE_string('base_dir', 'exp1', 'Base directory containing the experiment folders.')
flags.DEFINE_string('output_plot', 'summary_plot.png', 'Filename to save the generated plot.')

def parse_metrics(filepath):
    """Parses the last 8 lines of the file to find 'cnc' and 'win' values."""
    cnc_val = None
    win_val = None
    
    try:
        with open(filepath, 'r') as f:
            lines = f.readlines()
            
        # Focus only on the last 8 lines
        last_lines = lines[-8:] if len(lines) >= 8 else lines
        text_to_search = " ".join(last_lines).lower()
        
        # Regex to find 'cnc' and 'win' followed by =, :, or just spaces, then a number
        # Example matches: "cnc: 45.2", "win = 10", "cnc 0.5"
        cnc_match = re.search(r'cnc[^\d]*([-+]?\d*\.?\d+)', text_to_search)
        win_match = re.search(r'win[^\d]*([-+]?\d*\.?\d+)', text_to_search)
        
        if cnc_match:
            cnc_val = float(cnc_match.group(1))
        if win_match:
            win_val = float(win_match.group(1))
            
    except Exception as e:
        logging.error(f"Error reading {filepath}: {e}")
        
    return cnc_val, win_val

def main(argv):
    # Unused args
    del argv

    # Glob pattern to match files like exp1/exp1_forced_XXX_results/analysis.txt
    search_pattern = os.path.join(FLAGS.base_dir, '*_forced_*_results', 'analysis.txt')
    file_list = glob.glob(search_pattern)
    
    if not file_list:
        logging.warning(f"No files found matching pattern: {search_pattern}")
        return

    data = []

    # Regex to extract the OOV penalty (XXX) from the directory name
    # It looks for '_forced_', captures any integer (including negative), followed by '_results'
    dir_regex = re.compile(r'_forced_(-?\d+)_results')

    for filepath in file_list:
        match = dir_regex.search(filepath)
        if not match:
            logging.info(f"Could not extract OOV penalty from {filepath}, skipping.")
            continue
            
        oov_penalty = int(match.group(1))
        cnc, win = parse_metrics(filepath)
        
        if cnc is not None and win is not None:
            data.append((oov_penalty, cnc, win))
        else:
            logging.warning(f"Missing 'cnc' or 'win' in {filepath}")

    if not data:
        logging.error("No valid data extracted. Exiting.")
        return

    # Sort data primarily by OOV penalty so the line plot connects points correctly
    data.sort(key=lambda x: x[0])
    
    # Unzip the sorted data into separate lists for plotting
    oov_penalties, cnc_values, win_values = zip(*data)

    # Create the plot
    plt.figure(figsize=(10, 6))
    
    # Plot CNC and Win on the same graph
    plt.plot(oov_penalties, cnc_values, marker='o', linestyle='-', label='CNC', color='blue')
    plt.plot(oov_penalties, win_values, marker='s', linestyle='--', label='Win', color='orange')
    
    plt.title('CNC and Win Correct vs. OOV Penalty')
    plt.xlabel('OOV Penalty')
    plt.ylabel('Words Correct (%)')
    plt.grid(True, which='both', linestyle='--', alpha=0.7)
    plt.legend()
    
    # Save and optionally show the plot
    plt.tight_layout()
    plt.savefig(FLAGS.output_plot)
    logging.info(f"Plot saved successfully to {FLAGS.output_plot}")
    plt.show()

if __name__ == '__main__':
    app.run(main)
